# Определение версии Docker Compose и начало описания сервисов

services:
  # для удобства в IDE и запусках тестов
  alpine-django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-alpine
    depends_on:
      - pgdb

  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: order_django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8000 #python3 manage.py runserver_plus --cert-file cert.pem --key-file key.pem  #
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgis/postgis:17-3.6-alpine
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
    ports:
      - 5433:5432
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null